name: flutter_components
description: A new Flutter package project.
version: 1.0.0
homepage: https://github.com/vagnermdr/flutter_components

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  golden_toolkit: ^0.13.0

flutter:
  assets:
    - images/

  fonts:
    - family: Roboto
      fonts:
        - asset: packages/golden_toolkit/fonts/Roboto-Regular.ttf
